# Generated by Django 3.2.4 on 2021-06-07 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='gas',
            new_name='_gas',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='gas_capacity',
            new_name='_gas_capacity',
        ),
    ]
